-- =====================================================
-- ERROR LOG TABLE for Trigger Error Handling
-- =====================================================

CREATE TABLE error_log (
    error_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_message VARCHAR2(4000) NOT NULL,
    error_date DATE DEFAULT SYSDATE,
    table_name VARCHAR2(50),
    operation VARCHAR2(50),
    user_session VARCHAR2(100) DEFAULT USER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for performance
CREATE INDEX idx_error_log_date ON error_log(error_date);
CREATE INDEX idx_error_log_table ON error_log(table_name);
